name: dependapilot

services:
  php:
    image: ${IMAGES_PREFIX:-dependapilot}:dev-${IMAGES_TAG:-latest}
    restart: unless-stopped
    hostname: php
    environment:
      PHP_DATE_TIMEZONE: ${APP_TIMEZONE:-UTC}
      SERVER_NAME: localhost, php:80
      TZ: ${APP_TIMEZONE:-UTC}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ../:/app
      - ../var:/app/var
      - ./Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    ports:
      - name: http
        target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - name: https
        target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - name: http3
        target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

volumes:
  caddy_data:
  caddy_config:
